name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: gobzzz-g
          filename: github-metrics.svg

          # Base sections
          base: header, activity, community, repositories

          # Isometric contribution calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Programming languages
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8

          # Recently starred repositories
          plugin_stars: yes
          plugin_stars_limit: 4

          # Starred topics
          plugin_topics: yes
          plugin_topics_limit: 10
